### ISSUE TITLE
Can i get more info from the scanned file?

### ISSUE THREAD

**Issue by osc2nuke** [kissit/php-clamav-scan#3]
Is there a way to get a more information from the scanned file(s)?

Thanks in advance.

**Comment by kissit** [comment]
What kind of information are you looking for?

**Comment by osc2nuke** [comment]
The scan log itself and name of the virus if found one..

> ----------- SCAN SUMMARY -----------
Known viruses: 4724261
Engine version: 0.99
Scanned directories: 128878
Scanned files: 791920
Infected files: 29
Total errors: 25699
Data scanned: 187109.62 MB
Data read: 1683517.68 MB (ratio 0.11:1)
Time: 19860.535 sec (331 m 0 s)

**Comment by kissit** [comment]
I think you may misunderstand the way the class works.  That looks like the output from running a scan of a large directory tree using the "clamscan" CLI tool.  This class does not use clamscan but instead scans a single file directly against clamd using its local socket by issuing a raw "SCAN" command.  

The use case for this class has been for scanning one or a handful of files uploaded by a user through a web page as fast as possible, so having support for scanning via clamscan hasn't been a priority since it means loading the database each call.  

That being said I did add the ability to capture the name of a virus if one is detected, but again its still based on the expectation that the caller will handle any looping of multiple files or recursing a directory tree to build up such information as you show in your example.

The included test script shows how to get this message:
```
if($clamav->scan("/path/to/file/to/scan")) {
    echo "YAY, file is safe!\n";
} else {
    echo "BOO, file is a virus.  Message: " . $clamav->getMessage() . "\n";
}
```

Which gives this when run:
```
Testing a good file...
YAY, file is safe!

Testing a bad file...
BOO, file is a virus.  Message: Eicar-Test-Signature FOUND
```

**Comment by osc2nuke** [comment]
Good that you added that extra method to receive the response.
I am very aware how the class works. VERY aware.
I just not know how ClamAV handles any call-backs.
So :+1: +1 for adding the method `$clamav->getMessage() `

**Comment by osc2nuke** [comment]
Now to put it in a more suitable use case:
`echo *anything`
remove the hard-coded echo and just use getMessage() or better getRespond().

**Comment by osc2nuke** [comment]
Not force yourself to my comment.
I only notice.
I like simplicity, you provided me with that.
You are the master of this repository.
See my comment as just "hinting" you.
What you do with it.....it is up to you.
i like it.
